pyutils-unusedcode:
  exclude_files:
  - "my_exclude_file.py"
  exclude_function_prefix:
  - "my_exclude_function_prefix"
pyutils-polarion-verify-tc-requirements:
  project_id: "ABCDEF"
  branch_name: "origin/main"
pyutils-polarion-set-automated:
  project_id: "ABCDEF"
  branch_name: "origin/main"
