pyutils-unusedcode:
  exclude_files:
  - "my_exclude_file.py"
  exclude_function_prefix:
  - "my_exclude_function_prefix"
pyutils-polarion-verify-tc-requirements:
  project_id: "ABCDEF"
  branch: "origin/main"
pyutils-polarion-set-automated:
  project_id: "ABCDEF"
  branch: "origin/main"
pyutils-jira:
  url: <jira url>
  token: <jira token>
  resolved_statuses:
  - verified
  - release pending
  - closed
  issue_pattern: "([A-Z]+-[0-9]+)"
  skip_project_ids:
    - ABC
    - DEF
  jira_target_versions:
    - 1.0.0
  version_string_not_targeted_jiras: "not-targeted"
